package com.ironhack.midtermproject.enums;

public enum TransactionTypes {
    ACCOUNTTOACCOUNT, THIRDPARTYTOACCOUNT, ACCOUNTTOTHIRDPARTY, INTEREST, MAINTENANCE, PENALTY, ADMINTOACCOUNT, ADMINFROMACCOUNT
}
